### ISSUE TITLE
Error in utils.py pad_2d

### ISSUE THREAD

**Issue by YunzeMan** [snapfinger/pancreas-seg#2]
Hi Yijun, thanks for your sharing. The funtion **pad_2d** in **_utils.py_** may return None when the input plane is 'Y'. Is this a bug or you assume the parameter won't be 'Y'?

**Comment by YunzeMan** [comment]
Also, in slice.py, from ![line 59](https://github.com/snapfinger/pancreas-seg/blob/de188210a44004dbcc3a545fdbc838ab9ffc9e52/slice.py#L59), the indent seems to be wrong. I assume it should be in \_\_main\_\_ block.

**Comment by snapfinger** [comment]
Hi Yunze, you are right for both questions. 
For the first one, though I first experimented with different views of the image, I finally only used axial view for training, so I assume the input would only be `Z` for [this function](https://github.com/snapfinger/pancreas-seg/blob/master/utils.py#L26) (there's still a X choice there, and comments for the functions may be inconsistent mainly b/c the rush to finish the experiments at that time... Still, you can add your padding option similarly)
For the second one, I used vim most of the time, but edited the code several times in atom. Later I found the indent became strange (inconsistent) in several places shown on github, but I can run the code w/o problem on my machine if I pull it.
I may polish the code if I have time in the future. 
I will close this and feel free to add follow-up questions.
