### ISSUE TITLE
Model can predict image, Model return black image

### ISSUE THREAD

**Issue by namphn** [snapfinger/pancreas-seg#4]
Hi Yijun, thanks for your sharing.
I have prepared the data as instructed in the readme file
![image](https://user-images.githubusercontent.com/38358493/137196358-c2c8b765-27a4-46cc-924a-c2b34f7d5854.png)
![image](https://user-images.githubusercontent.com/38358493/137196383-acbd2f58-7d04-4afa-9474-9a9521a1a162.png)

And when I run the program, I get some errors and make corrections like below:
change: https://github.com/snapfinger/pancreas-seg/blob/6d640676e5b398452e2de6f992bd4dfea78ed2c8/slice.py#L65
```
image = np.load(image_list[i])
label = np.load(label_list[i]))
```
to
```
image = np.load(image_list[i])
label = np.array(nibabel.load(label_list[i]).dataobj)
```

same here: https://github.com/snapfinger/pancreas-seg/blob/6d640676e5b398452e2de6f992bd4dfea78ed2c8/testvis.py#L75

I modify variable in pipeline as below:
ZMAX=160
YMAX=256
XMAX=256

model gave incorrect prediction:
![image](https://user-images.githubusercontent.com/38358493/137197611-87588e55-cfb1-43b2-b65d-99b84c34186d.png)

can you help me? plz!

**Comment by snapfinger** [comment]
Hi @namph-uet, are you using the same environment settings as the readme ones? (you can check your package versions by `pip list`) It's a project quite a few years ago, so these settings (e.g python 2.7) are kind of outdated, but can ensure you get the same results. 

According to what you described, I guess you used a different version of at least one of the packages. The numerical operation behavior can be different in newer versions. For example, for integer divisions 20 / 15, python 2 will give 1, while python 3 will give 1.333333  This will affect your your output image.

I don't think the part you posted has an effect on the output, but you need to check the intermediate data type in your computation. Or you simply setup the environment using the same old versions.
